In [1]:
import numpy as np

In [2]:
t1 = np.arange(9)
print(t1)



[0 1 2 3 4 5 6 7 8]


In [3]:
t2 = t1.reshape(3,3)
print(t2)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
m1 = np.ones(9).all()
print(m1)



True


In [6]:
print(np.array([1,0,2]).all())

False


In [7]:
print(np.array([[1,0,2],[1,2,3]]).all(axis=0))


[ True False  True]


In [8]:
t2 = np.array([[1,0,2],[0,0,2]])
print(t2.any())


True


In [9]:
print(t2.any(axis=1))


[ True  True]


In [10]:
t3 = t2
print("t2: ",id(t2)," t3:",id(t3))


t2:  2056427678736  t3: 2056427678736


In [11]:
t4 = t3.copy()
print("t4:",id(t4))


t4: 2056429172816


In [12]:
a1 = np.ones(9,dtype=float)
print(a1)


[1. 1. 1. 1. 1. 1. 1. 1. 1.]
