In [2]:
import numpy as np

A = np.array([[1,2,3,4],[5,6,7,8]])



In [3]:
A.reshape((4,-1))




array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
A.reshape((4,2),order="F")



array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [6]:
A[1,:]


array([5, 6, 7, 8])

In [8]:
A[:,2]


array([3, 7])

In [9]:
A[0:2,1:3]


array([[2, 3],
       [6, 7]])

In [11]:
B = np.array([A,A*2])
print(B)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 2  4  6  8]
  [10 12 14 16]]]


In [12]:
np.linspace(start=1,stop=15,num=5)

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [13]:
np.arange(1,15.5)



array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [14]:
np.zeros((2,3))



array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.diag(np.arange(1,15,5))


array([[ 1,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 11]])

In [18]:
np.diag(np.arange(9).reshape((3,3)))


array([0, 4, 8])

In [20]:
np.random.seed(2)
np.random.randn(3,3)

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809, -1.05795222]])

In [21]:
np.random.seed(2)
C = np.random.randn(3,3).T
print(C)


[[-0.41675785  1.64027081  0.50288142]
 [-0.05626683 -1.79343559 -1.24528809]
 [-2.1361961  -0.84174737 -1.05795222]]


In [22]:
D = np.mat(C).I
print(D)


[[ 0.42265324  0.65304428 -0.5677797 ]
 [ 1.29443848  0.7541515  -0.2724006 ]
 [-1.88331793 -1.91864589  0.41795959]]


In [23]:
np.mat(C)*D


matrix([[ 1.00000000e+00,  8.43337040e-17,  4.42548666e-17],
        [-3.43586150e-16,  1.00000000e+00, -2.49601463e-17],
        [-2.40764231e-17,  2.01146775e-16,  1.00000000e+00]])

In [24]:
np.linalg.det(C)


2.0090965940791263

In [25]:
np.trace(C)


-3.2681456514626728

In [26]:
E = np.arange(10)
print(E)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
E.mean()


4.5

In [28]:
E.std()


2.8722813232690143

In [30]:
np.median(E)


4.5

In [31]:
np.percentile(E,50)

4.5

In [32]:
np.sort([[2,5,3],[6,8,10]],axis=1)


array([[ 2,  3,  5],
       [ 6,  8, 10]])

In [33]:
np.sort([[2,6,5],[4,9,7]],axis=0)


array([[2, 6, 5],
       [4, 9, 7]])