In [2]:
import numpy as np

In [3]:
h1 = np.arange(5)

In [6]:
h2 = np.arange(0,5)

In [7]:
h3 = np.arange(0,5,0.5)
print(h3)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [8]:
h4 = np.arange(5,0,-1)
print(h4)

[5 4 3 2 1]


In [9]:
i0 = np.linspace(0,1,2)
print(i0)


[0. 1.]


In [10]:
i1 = np.linspace(0,4,4)
print(i1)



[0.         1.33333333 2.66666667 4.        ]


In [11]:
i2 = np.linspace(0,4,10)
print(i2)



[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]


In [12]:
z1 = np.zeros(5)
print(z1)



[0. 0. 0. 0. 0.]


In [13]:
z2 = np.zeros((3,3),int)
print(z2)




[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
o1 = np.ones((2,3),int)
print(o1)



[[1 1 1]
 [1 1 1]]


In [15]:
e10 = np.empty(5)
print(e10)



[0. 0. 0. 0. 0.]


In [16]:
e11 = np.empty((4,4))
print(e11)



[[6.23042070e-307 1.89146896e-307 1.89146896e-307 1.37961302e-306]
 [1.05699242e-307 1.95821439e-306 3.11523412e-307 1.78022342e-306]
 [1.05700345e-307 1.11261977e-306 2.22523140e-306 1.02360867e-306]
 [1.86921958e-306 6.89804133e-307 1.11261162e-306 8.34443015e-308]]


In [17]:
log12 = np.logspace(2.0,3.0,4)
print(log12)

[ 100.          215.443469    464.15888336 1000.        ]


In [18]:
f10 = np.full(5,10)
print(f10)


[10 10 10 10 10]


In [19]:
f11 = np.full((3,3),8)
print(f11)


[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [20]:
eye12 = np.eye(4)
print(eye12)



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
repeat12 = np.repeat([0,1,2],5)
print(repeat12)


[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


In [22]:
ar1 = np.array([['a','b','c'],['d','e','f'],['g','h','i']])
print(ar1)



[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]


In [23]:
print(ar1.ndim)

2


In [24]:
print(ar1.shape)



(3, 3)


In [25]:
print(ar1.size)



9


In [26]:
print(ar1.dtype)


<U1


In [27]:
print(ar1.itemsize)

4
